<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Menu;
use Carbon\Carbon;
use Spatie\Permission\Models\Permission;

class MenuSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run ()
    {
        $now         = Carbon::now ();

        $menus = [ 
            [ 
                'id'            => 1,
                'label'         => 'Dashboard',
                'serial'        => '1.00',
                'route'         => 'dashboard',
                'parent_id'     => null,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => null,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 2,
                'label'         => 'User Access Control',
                'serial'        => '2.00',
                'route'         => null,
                'parent_id'     => null,
                'permission_id' => null,
                'icon'          => 'ri-admin-line',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => null,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 3,
                'label'         => 'User List',
                'serial'        => '2.10',
                'route'         => 'users.index',
                'parent_id'     => 2,
                'permission_id' => null,
                'icon'          => 'ri-record-circle-line',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 4,
                'label'         => 'Menu List',
                'serial'        => '2.40',
                'route'         => 'menus.index',
                'parent_id'     => 2,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 5,
                'label'         => 'Basic Setup',
                'serial'        => '3.00',
                'route'         => null,
                'parent_id'     => null,
                'permission_id' => null,
                'icon'          => 'ri-user-settings-fill',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 6,
                'label'         => 'Country List',
                'serial'        => '3.10',
                'route'         => 'countries.index',
                'parent_id'     => 5,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 7,
                'label'         => 'Skill List',
                'serial'        => '3.20',
                'route'         => 'skills.index',
                'parent_id'     => 5,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 8,
                'label'         => 'Role List',
                'serial'        => '2.20',
                'route'         => 'roles.index',
                'parent_id'     => 2,
                'permission_id' => null,
                'icon'          => 'ri-admin-line',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 9,
                'label'         => 'Permission List',
                'serial'        => '2.30',
                'route'         => 'permissions.index',
                'parent_id'     => 2,
                'permission_id' => null,
                'icon'          => 'ri-admin-line',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => null,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 10,
                'label'         => 'Document List',
                'serial'        => '3.30',
                'route'         => 'documents.index',
                'parent_id'     => 5,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => null,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 11,
                'label'         => 'Top Up Configuration',
                'serial'        => '8.40',
                'route'         => 'top-ups.index',
                'parent_id'     => 23,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 12,
                'label'         => 'Commission Configuration',
                'serial'        => '8.30',
                'route'         => 'commissions.index',
                'parent_id'     => 23,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 13,
                'label'         => 'Transactions',
                'serial'        => '4.00',
                'route'         => null,
                'parent_id'     => null,
                'permission_id' => null,
                'icon'          => 'bx bx-money',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 14,
                'label'         => 'Subscription List',
                'serial'        => '4.20',
                'route'         => 'subscriptions.index',
                'parent_id'     => 13,
                'permission_id' => null,
                'icon'          => 'bx bx-list-ul',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => null,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 15,
                'label'         => 'Subscription History',
                'serial'        => '4.30',
                'route'         => 'subscriptions.history',
                'parent_id'     => 13,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 16,
                'label'         => 'Transaction List',
                'serial'        => '4.10',
                'route'         => 'transactions.index',
                'parent_id'     => 13,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 17,
                'label'         => 'Bookings',
                'serial'        => '5.00',
                'route'         => null,
                'parent_id'     => null,
                'permission_id' => null,
                'icon'          => 'ri-contacts-book-2-line',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 18,
                'label'         => 'Reviews & Ratings',
                'serial'        => '5.20',
                'route'         => 'ratings.index',
                'parent_id'     => 17,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => null,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 19,
                'label'         => 'Booking List',
                'serial'        => '5.10',
                'route'         => 'bookings.index',
                'parent_id'     => 17,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => null,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 20,
                'label'         => 'Refunds',
                'serial'        => '4.60',
                'route'         => 'refunds.index',
                'parent_id'     => 13,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => null,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 21,
                'label'         => 'Client',
                'serial'        => '6.00',
                'route'         => 'clients.index',
                'parent_id'     => null,
                'permission_id' => null,
                'icon'          => 'ri-user-star-fill',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 22,
                'label'         => 'Professional',
                'serial'        => '7.00',
                'route'         => 'professionals.index',
                'parent_id'     => null,
                'permission_id' => null,
                'icon'          => 'ri-user-location-line',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 23,
                'label'         => 'Configuration',
                'serial'        => '8.00',
                'route'         => null,
                'parent_id'     => null,
                'permission_id' => null,
                'icon'          => 'ri-settings-4-line',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 24,
                'label'         => 'Navigation',
                'serial'        => '8.10',
                'route'         => 'navigations.index',
                'parent_id'     => 23,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 25,
                'label'         => 'Cancel Reasons',
                'serial'        => '8.20',
                'route'         => 'cancel-reasons.index',
                'parent_id'     => 23,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 26,
                'label'         => 'Support System',
                'serial'        => '9.00',
                'route'         => null,
                'parent_id'     => null,
                'permission_id' => null,
                'icon'          => 'ri-lifebuoy-line',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 27,
                'label'         => 'Professional Map',
                'serial'        => '8.50',
                'route'         => 'map',
                'parent_id'     => 23,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 28,
                'label'         => 'CMS Pages',
                'serial'        => '8.60',
                'route'         => 'cms-pages.index',
                'parent_id'     => 23,
                'permission_id' => null,
                'icon'          => 'bi bi-grid',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 30,
                'label'         => 'SOS Numbers',
                'serial'        => '9.20',
                'route'         => 'sos-numbers.index',
                'parent_id'     => 26,
                'permission_id' => null,
                'icon'          => 'ri-record-circle-line',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 31,
                'label'         => 'SOS Requests',
                'serial'        => '9.30',
                'route'         => 'sos-requests.index',
                'parent_id'     => 26,
                'permission_id' => null,
                'icon'          => 'ri-record-circle-line',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 32,
                'label'         => 'Customer Support',
                'serial'        => '9.10',
                'route'         => 'customer-supports.index',
                'parent_id'     => 26,
                'permission_id' => null,
                'icon'          => 'ri-record-circle-line',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
            [ 
                'id'            => 33,
                'label'         => 'Country Area List',
                'serial'        => '3.40',
                'route'         => 'country-areas.index',
                'parent_id'     => 5,
                'permission_id' => null,
                'icon'          => 'ri-record-circle-line',
                'status'        => 1,
                'created_by'    => 1,
                'updated_by'    => 1,
                'deleted_by'    => null,
                'created_at'    => $now,
                'updated_at'    => $now,
                'deleted_at'    => null,
            ],
        ];

        $permissions = Permission::all ()->keyBy ( 'name' );
       
        foreach ( $menus as &$menu ) {
            if ( $menu[ 'route' ] && isset ( $permissions[ $menu[ 'route' ] ] ) ) {
                $menu[ 'label' ]         = $permissions[ $menu[ 'route' ] ]->display_name;
                $menu[ 'permission_id' ] = $permissions[ $menu[ 'route' ] ]->id;
            }
        }

        unset ( $menu );

        Menu::insertOrIgnore ( $menus );

    }
}
